#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

import { loadState, saveState } from './state.js';
import {
  listOpenPulls,
  listIssueCommentsForPr,
  listReviewCommentsForPr,
  createIssueComment
} from './github.js';
import { getOpenAIClient, generatePatch } from './ai.js';
import { enqueueNotification } from './notify.js';

function log(obj) {
  console.log(JSON.stringify({ ts: new Date().toISOString(), ...obj }));
}

function sh(cmd, opts = {}) {
  return execSync(cmd, { stdio: 'pipe', encoding: 'utf8', ...opts });
}

function getRepoFullName(repoPath) {
  const url = sh('git remote get-url origin', { cwd: repoPath }).trim();
  const m = url.match(/github\.com[:/](.+?)\/?(\.git)?$/);
  if (!m) throw new Error(`Cannot parse GitHub repo from origin URL: ${url}`);
  return m[1];
}

function resetWorkspace(repoPath) {
  sh('git reset --hard', { cwd: repoPath });
  sh('git clean -fd', { cwd: repoPath });
}

function checkoutPrBranch(repoPath, branch) {
  sh(`git checkout ${branch}`, { cwd: repoPath });
  sh('git pull --rebase', { cwd: repoPath });
}

function getRepoSnapshot(repoPath) {
  // Minimal context: list + key files only (can be improved later).
  const files = ['README.md', 'package.json', 'next.config.ts', 'app/page.tsx'];
  let snap = '';
  for (const f of files) {
    const p = path.join(repoPath, f);
    if (fs.existsSync(p)) {
      const content = fs.readFileSync(p, 'utf8').slice(0, 6000);
      snap += `\n---\nFILE: ${f}\n${content}\n`;
    }
  }
  return snap.slice(0, 24000);
}

function applyPatch(repoPath, patchText) {
  const tmp = path.join(repoPath, '.openclaw.patch');
  fs.writeFileSync(tmp, patchText);
  try {
    sh(`git apply --whitespace=fix ${tmp}`, { cwd: repoPath });
  } finally {
    fs.unlinkSync(tmp);
  }
}

function runChecks(repoPath) {
  sh('npm run lint', { cwd: repoPath, stdio: 'pipe' });
  sh('npm run build', { cwd: repoPath, stdio: 'pipe' });
}

function commitAndPush(repoPath) {
  sh('git add -A', { cwd: repoPath });
  // If no changes, do nothing.
  try {
    sh('git diff --cached --quiet', { cwd: repoPath });
    return null;
  } catch {
    // has staged changes
  }

  sh('git commit -m "chore: address PR comment\n\nGenerated by OpenClaw"', { cwd: repoPath });
  sh('git push', { cwd: repoPath });
  const sha = sh('git rev-parse HEAD', { cwd: repoPath }).trim();
  return sha;
}

function selectFirstValidComment({ comments, processedIds, botLogin }) {
  const sorted = comments.slice().sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
  for (const c of sorted) {
    const id = String(c.id);
    if (processedIds.has(id)) continue;
    if (c.user?.login === botLogin) continue;
    return c;
  }
  return null;
}

async function main() {
  const argv = process.argv.slice(2);
  const dryRun = argv.includes('--dry-run');
  const backfillPrArgIndex = argv.indexOf('--backfill-pr');
  const backfillPr = backfillPrArgIndex >= 0 ? Number(argv[backfillPrArgIndex + 1]) : null;

  const configPath = path.join(path.dirname(new URL(import.meta.url).pathname), 'config.json');
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

  const state = loadState();
  const processed = new Set(state.processedCommentIds.map(String));

  log({ event: 'run_start', lastCursor: state.lastCursor, dryRun, backfillPr });

  // Determine bot login from gh
  const botLogin = sh('gh api user --jq .login').trim();

  const nowISO = new Date().toISOString();

  for (const repoPath of config.repos) {
    const repoFullName = getRepoFullName(repoPath);
    log({ event: 'repo_start', repoFullName, repoPath });

    let prs;
    try {
      prs = listOpenPulls(repoFullName);
    } catch (e) {
      log({ event: 'error', stage: 'listOpenPulls', repoFullName, error: String(e) });
      continue;
    }

    for (const pr of prs.sort((a, b) => new Date(a.updatedAt) - new Date(b.updatedAt))) {
      const prNumber = pr.number;
      if (backfillPr && prNumber !== backfillPr) continue;

      let issueComments = [];
      let reviewComments = [];
      const sinceISO = backfillPr ? new Date(0).toISOString() : state.lastCursor;

      try {
        issueComments = listIssueCommentsForPr(repoFullName, prNumber, sinceISO);
      } catch (e) {
        log({ event: 'error', stage: 'listIssueComments', prNumber, error: String(e) });
      }
      try {
        reviewComments = listReviewCommentsForPr(repoFullName, prNumber, sinceISO);
      } catch (e) {
        log({ event: 'error', stage: 'listReviewComments', prNumber, error: String(e) });
      }

      // Normalize to same shape
      const normalized = [];
      for (const c of issueComments) {
        normalized.push({
          kind: 'issue_comment',
          id: c.id,
          created_at: c.created_at,
          body: c.body,
          user: c.user,
          prNumber
        });
      }
      for (const c of reviewComments) {
        normalized.push({
          kind: 'review_comment',
          id: c.id,
          created_at: c.created_at,
          body: c.body,
          user: c.user,
          prNumber
        });
      }

      const selected = selectFirstValidComment({ comments: normalized, processedIds: processed, botLogin });
      if (!selected) continue;

      log({
        event: 'selected_comment',
        repoFullName,
        prNumber,
        commentId: String(selected.id),
        kind: selected.kind,
        author: selected.user?.login
      });

      // Prepare workspace
      resetWorkspace(repoPath);

      // Checkout PR branch
      const branch = pr.headRefName;
      try {
        checkoutPrBranch(repoPath, branch);
      } catch (e) {
        // PR branch might not exist locally; fetch and retry
        try {
          sh(`git fetch origin ${branch}:${branch}`, { cwd: repoPath });
          checkoutPrBranch(repoPath, branch);
        } catch (e2) {
          log({ event: 'error', stage: 'checkout', prNumber, branch, error: String(e2) });
          processed.add(String(selected.id));
          saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
          return;
        }
      }

      // AI patch generation
      const client = getOpenAIClient();
      const repoSnapshot = getRepoSnapshot(repoPath);
      const instruction = selected.body || '';

      let patch;
      try {
        patch = await generatePatch({ client, instruction, repoSnapshot });
      } catch (e) {
        log({ event: 'error', stage: 'ai', prNumber, error: String(e) });
        processed.add(String(selected.id));
        saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
        return;
      }

      // Apply patch (retry once after rebase if conflict)
      try {
        applyPatch(repoPath, patch);
      } catch (e) {
        log({ event: 'patch_apply_failed', prNumber, error: String(e) });
        try {
          sh('git pull --rebase', { cwd: repoPath });
          applyPatch(repoPath, patch);
        } catch (e2) {
          if (!dryRun) {
            createIssueComment(repoFullName, prNumber, 'Failed to apply patch cleanly. Please rebase or clarify the change.');
          }
          processed.add(String(selected.id));
          saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
          return;
        }
      }

      // Run checks
      try {
        runChecks(repoPath);
      } catch (e) {
        const msg = 'Lint/build failed after applying the change. Please check logs locally.';
        if (!dryRun) {
          createIssueComment(repoFullName, prNumber, msg);
        }
        log({ event: 'checks_failed', prNumber, error: String(e) });
        processed.add(String(selected.id));
        saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
        return;
      }

      if (dryRun) {
        log({ event: 'dry_run_done', prNumber });
        processed.add(String(selected.id));
        saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
        return;
      }

      // Commit & push
      let sha;
      try {
        sha = commitAndPush(repoPath);
      } catch (e) {
        createIssueComment(repoFullName, prNumber, 'Push failed (permission or authentication issue).');
        log({ event: 'push_failed', prNumber, error: String(e) });
        processed.add(String(selected.id));
        saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
        return;
      }

      if (sha) {
        const commitUrl = `https://github.com/${repoFullName}/commit/${sha}`;
        createIssueComment(repoFullName, prNumber, `Addressed in commit: ${commitUrl}`);
        log({ event: 'success', prNumber, sha, commitUrl });
        enqueueNotification({
          level: 'info',
          kind: 'success',
          repo: repoFullName,
          prNumber,
          commentId: String(selected.id),
          commitUrl
        });
      } else {
        createIssueComment(repoFullName, prNumber, 'No code changes were needed.');
        log({ event: 'no_changes', prNumber });
      }

      processed.add(String(selected.id));
      saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
      return; // only one comment per run
    }
  }

  // Update cursor even if no comment processed
  saveState({ lastCursor: nowISO, processedCommentIds: Array.from(processed) });
  log({ event: 'run_end', status: 'noop', lastCursor: nowISO });
}

main().catch(err => {
  const msg = String(err);
  log({ event: 'fatal', error: msg });
  try {
    enqueueNotification({ level: 'error', kind: 'fatal', error: msg });
  } catch {
    // ignore
  }
  process.exitCode = 1;
});
